POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZXhhbXBsZS5jb20iLCJleHAiOjE3Mjc5NDUyNjYsInVzZXJJZCI6MX0.Sk21d-l3fdzRuLL8nI_CJL1yHqDw0CviUuPiOUiQyhc

{
    "name": "Test event 1",
    "description": "A test event 1",
    "location": "A test location 1",
    "dateTime": "2025-01-01T15:30:00.000Z"
}